### ISSUE TITLE
Removal of version number in composer.json has broken this plugin on my existing Magento 2 install.

### ISSUE THREAD

**Issue by quangdog** [Nofraud/nofraud_connect#29]
Yesterday I upgraded my Magento store, and during that upgrade, of course the NoFraudConnect plugin was also updated. When the update was completed, I started seeing these errors in my store's exception log: 

```
*** exception.log ***
[2023-06-30 21:37:13] main.CRITICAL: Notice: Undefined index: version in /var/www/miridiatech/vendor/nofraud/connect/Block/Adminhtml/System/Config/Fieldset/Version.php on line 49 {"exception":"[object] (Exception(code: 0): Notice: Undefined index: version in /var/www/miridiatech/vendor/nofraud/connect/Block/Adminhtml/System/Config/Fieldset/Version.php on line 49 at /var/www/miridiatech/vendor/magento/framework/App/ErrorHandler.php:61)"} []
```

Note that the core issue here is that the NoFraud plugin itself is looking in it's own composer.json file for a field named "version". I was puzzled why it would not be there, so I went and looked in the composer.json file in the plugin and discovered that the version has indeed been removed. 

I then came here to the git repo to see *when* it was removed, and it appears to have been a very recent change. 

I added "version":"1.0.0", back into the composer.json, and the plugin is working again... but the next time I do a store update, this will just break unless you either put the version back into the plugin or remove the references to it in the plugin.

As a side note: Your install instructions indicate that to install the plugin you should ```composer require nofraud/connect dev-master``` - I suggest this should be changed to use a specific version numbering system rather than just "pull from the head of our git repo", so as to avoid store-breaking problems such as this.

**Comment by soleilcot** [comment]
Hi! Thanks for bringing this up. The intention behind this was to get behind the composer recommendation that version key be omitted when a VCS is used and the package is published to packagist. However, as you mentioned there is a FE dependency here that was overlooked which would cause the fatal exception upon accessing the admin settings page for the plugin.

I don't believe this error would have affected the processing of orders on the store since the only reference appears to be on that admin view. In any case, we have pushed a hot fix version v1.0.1 which should prevent the bad version from being pulled.

You are also right that pulling from dev-master is not needed. Since semantic versioning is in use on this repo, `composer require nofraud/connect` should be enough to get the latest tag pulled.
